all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/user/Google'
vk_url: ''
whatsapp_url: ''
github_url: ''
telegram_url: ''
vimeo_url: ''
slider_show: 1
slider_image:
  - '4'
slider_time: '5000'
slider_dots: 'true'
slider_code: "<li>\r\n<h1> WELCOME TO THE OCEAN</h1>\r\n<a class=\"button\" href=\"#\">Get Started</a>\r\n</li><li>\r\n<h1> Choose the blogs You Like</h1>\r\n<a class=\"button\" href=\"#\">Get Started</a>\r\n</li><li>\r\n<h1> Join US And Become A Contributer TO Good</h1>\r\n<a class=\"button\" href=\"\">Get Started</a>\r\n</li>"
front_sidebar: 1
google_font: local
comment_user_pic: 0
node_author_pic: 0
node_tags: 0
copyright_text: 1
scrolltotop_on: 1
css_extra: 1
css_code: ".home-slider h1{\r\ncolor : white;\r\n}\r\n.home-slider a.button{\r\nbackground-color: aqua;\r\n}"
_core:
  default_config_hash: 6r9KA1Wa13n0_l8yU0AP5GKn49rkKotIYeyrdd22qac
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo.png'
favicon:
  use_default: false
  path: 'public://logo_0.png'
  mimetype: image/png
