# Schema for configuration files of the Square Pixels Scale module.

image.effect.square_pixels_scale:
  type: image_size
  label: 'Square pixels scale'
  mapping:
    square_pixels:
      type: integer
      label: 'Square pixels'
    max_width:
      type: integer
      label: 'Maximum width'
    max_height:
      type: integer
      label: 'Maximum height'
    upscale:
      type: boolean
      label: 'Upscale'
